# Generated by Django 4.1.7 on 2023-03-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_alter_post_body_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='footnote',
            field=models.CharField(default='Puodelis po puodelio', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='Įeikite į straipsnį, kad perskaityti', max_length=255),
        ),
    ]
